config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users
  get 'semester/index'
  get 'semester/:id', to: 'semester#show', as: 'semester'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :speakers
  resources :talks

  namespace :api do
    resources :speakers
    resources :talks
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  root to: 'home#index'

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_many :talks, dependent: :destroy
  has_many :semesters, through: :talks
end

app/controllers/api/speakers_controller.rb
class Api::SpeakersController < Api::ApiController

  before_action :set_speaker, only: [:show, :update, :destroy]

  before_action do
    request.format = :json
  end

  def index
    @speakers = Speaker.all
  end

  def show
  end

  def create
    @speaker = Speaker.find_or_initialize_by(email: params[:email])
    if @speaker.new_record?
      @speaker.name = params[:name]
      @speaker.pic = "https://placeimg.com/640/480/tech"
      @speaker.save
    end
    talk = @speaker.talks.new
    talk.semester = Semester.last
    talk.date = params[:talk_date]
    talk.save!

      render json: @speaker
  end

  def update
    if @speaker.update(speaker_params)
      render :show, status: :ok, location: @speaker
    else
      render json: @speaker.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @speaker.destroy
    format.json { head :no_content }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speaker
      @speaker = Speaker.find_by!(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speaker_params
      params.require(:speaker).permit(:name, :pic, :company, :email, :title, :semester_id, :talk_date, talk_ids: [])
    end
end

app/controllers/api/v1/speakers.rb
module API
  module V1
    class Speakers < Grape::API
      include API::V1::Defaults

      resource :speakers do
        desc "Return all speakers"
              params do
                optional :start_date, type: Date, desc: "Start Date of Semester"
              end

              get "", root: :speakers do

                query = Speaker.all

                if permitted_params[:start_date].present?
                query = query.joins(:semester => :speaker).where("semester.start_date" => params[:start_date])
                # query = query.where(start_date: permitted_params[:start_date]) if permitted_params[:start_date].present?
                end

                query
              end

        desc "Return a speaker"
        params do
          requires :id, type: String, desc: "ID of the speaker"
        end
        get ":id", root: "speaker" do
          Speaker.where(id: permitted_params[:id]).first!
        end
      end
    end
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < InheritedResources::Base

def index

    @speakers = Speaker.all

end



  private



    def speaker_params
      params.require(:speaker).permit(:name, :date, :pic, :company, :email, :title, :semester_id)
    end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/speakers/_form.html.erb
<%= form_for(@speaker) do |f| %>
  <% if @speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% @speaker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :pic %><br>
    <%= f.text_field :pic %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :semester %><br>
    <%= f.collection_select :semester_id, Semester.order(:start_date),:id,:start_date, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
<h1>Editing Speaker</h1>

<%= render 'form' %>

<%= link_to 'Show', @speaker %> |
<%= link_to 'Back', speakers_path %>

app/views/speakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guest Speakers </h1>


<% @speakers.each do |speaker| %>
<div class="col-md-3">
  <div class="card">
    <div class="card-content">
      <div class="card-image">
        <%= image_tag(speaker.pic, class: "card-image img-resposive img-thumbnail") %>
      </div>
          <div class="card-body">
            <h4><%= mail_to speaker.email, speaker.name %></h4>
            <p>Company - <%= speaker.company %></p>
            <p>Title - <%= speaker.title %></p>
            <p>Date - <%= speaker.talks.pluck(:date).last.strftime('%m/%d/%Y') %></p>
          </div>
    </div>
  </div>
</div>
<% end %>

app/views/speakers/new.html.erb
<h1>New Speaker</h1>

<%= render 'form' %>

<%= link_to 'Back', speakers_path %>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="mdl-grid center">
  <div class="mdl-cell mdl-cell--6-col">
    <div class="center"><%= image_tag @speaker.pic, class: "circle" %></div>
      <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
        <div class="mdl-tabs__tab-bar">
            <a href="#contact" class="mdl-tabs__tab is-active">Contact</a>
            <a href="#company" class="mdl-tabs__tab">Company</a>
        </div>
        <div class="mdl-tabs__panel is-active" id="contact">
          <h2 class="center"><%= @speaker.name %></h2>
          <div class="center">
            <% if @speaker.email? %>
              <%= mail_to @speaker.email do image_tag "email.png" end %>
            <% end %>
            <% if @speaker.twitter? %>
              <%= link_to @speaker.twitter do image_tag "twitter.png" end %>
            <% end %>
            <% if @speaker.linkedin? %>
              <%= link_to @speaker.linkedin do image_tag "linkedin.png" end %>
            <% end %>
            <% if @speaker.github? %>
              <%= link_to @speaker.github do image_tag "github.png" end %>
            <% end %>
            </div>
            <div class="center">
              <% if @speaker.bio? %>
                <h6>  <%= @speaker.bio %></h6>

              <% end %>
            </div>



        </div>
        <div class="mdl-tabs__panel" id="company">
          <% if @speaker.company_logo? %>
            <h5 class="center"><%= link_to @speaker.company_url do image_tag @speaker.company_logo end %></h5>
          <% else %>
            <h5 class="center"><%= link_to @speaker.company_url %></h5>
          <% end %>
          <h5><b>Title:</b> <%= @speaker.title %></h5>
          <% if @speaker.company_about? %>
            <h6><b>About:</b><br> <%= @speaker.company_about %></h6>
          <% end %>
        </div>
      </div>
  </div>

</div>